name: Deploy to Firebase Hosting on Push
'on': push
jobs:
    deploy:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: npm install    
      - name: Build App
        run: npm run build
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.3
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_REACTDEMO_PH }}'
          projectId: reactdemo-ph
          channelId: live
